import pandas as pd
from ta.trend import SMAIndicator, EMAIndicator, MACD
from ta.momentum import RSIIndicator
from ta.volatility import BollingerBands

def add_technical_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """
    Adds technical indicators to the stock dataframe.
    Requires a 'Close' column.
    """
    if 'Close' not in df.columns:
        raise ValueError("Dataframe must contain 'Close' column for technical indicators.")
    
    df_features = df.copy()
    close_series = df_features['Close']
    
    # 1. Simple Moving Averages (SMA)
    df_features['SMA_14'] = SMAIndicator(close=close_series, window=14).sma_indicator()
    df_features['SMA_50'] = SMAIndicator(close=close_series, window=50).sma_indicator()
    
    # 2. Exponential Moving Averages (EMA)
    df_features['EMA_14'] = EMAIndicator(close=close_series, window=14).ema_indicator()
    df_features['EMA_50'] = EMAIndicator(close=close_series, window=50).ema_indicator()
    
    # 3. Relative Strength Index (RSI)
    df_features['RSI_14'] = RSIIndicator(close=close_series, window=14).rsi()
    
    # 4. Moving Average Convergence Divergence (MACD)
    macd = MACD(close=close_series)
    df_features['MACD'] = macd.macd()
    df_features['MACD_Signal'] = macd.macd_signal()
    df_features['MACD_Diff'] = macd.macd_diff()
    
    # 5. Bollinger Bands
    bb = BollingerBands(close=close_series, window=20, window_dev=2)
    df_features['BB_High'] = bb.bollinger_hband()
    df_features['BB_Low'] = bb.bollinger_lband()
    df_features['BB_Mid'] = bb.bollinger_mavg()
    
    # Additional basic features
    # Daily Return
    df_features['Daily_Return'] = close_series.pct_change()
    
    # Future Return (Target variable for ML) - Predict next day's return
    df_features['Target_Return_1d'] = df_features['Daily_Return'].shift(-1)
    
    # Target Direction (1 if Up, 0 if Down)
    df_features['Target_Direction'] = (df_features['Target_Return_1d'] > 0).astype(int)
    
    # Drop rows with NaN values generated by rolling windows or shifts (optional, depending on use case)
    # df_features.dropna(inplace=True)
    
    return df_features

if __name__ == "__main__":
    # Quick test
    import sys
    import os
    sys.path.append(os.path.dirname(os.path.abspath(__file__)))
    from data_loader import load_stock_data, get_all_symbols
    
    symbols = get_all_symbols()
    if symbols:
        df = load_stock_data(symbols[0])
        df_feat = add_technical_indicators(df)
        print(df_feat[['Close', 'SMA_14', 'RSI_14', 'MACD', 'BB_High', 'Target_Direction']].tail())
